[project]
name = "coctione_libri"
version = "0.1.0"
description = ""
authors = [{ name = "Peter Borocz", email = "680893+PBorocz@users.noreply.github.com" }]
requires-python = ">=3.11.0,<4.0"
readme = "README.md"
dependencies = [
    "flask>=3.0.0,<4",
    "flask-htmx>=0.3.2,<0.4",
    "flask-login>=0.6.3,<0.7",
    "pydantic>=2.5.3,<3",
    "python-dotenv>=1.0.0,<2",
    "secure>=0.3.0,<0.4",
    "rich>=13.7.0,<14",
    "wtforms>=3.1.2,<4",
    "flask-wtf>=1.2.1,<2",
    "email-validator>=2.1.0.post1,<3",
    "dynaconf>=3.2.4,<4",
    "flask-debugtoolbar>=0.14.1,<0.15",
    "tomli-w>=1.0.0,<2",
    "pandas>=2.2.2,<3",
    "matplotlib>=3.9.0,<4",
    "humanize>=4.11.0,<5",
    "pymongo>=4.10.1,<5",
    "mongoengine>=0.29.1,<0.30",
    "gunicorn>=23.0.0,<24",
    "boto3>=1.37.35,<2",
    "urllib3>=2.5.0,<3",
    "jinja2>=3.1.6,<4",
]

[dependency-groups]
dev = ["flask-debugtoolbar-mongo>=0.1,<0.2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.poe.tasks.deploy]
help = "Deploy to github on behalf of a production release."
shell = """
  jj bookmark set --revision  @- trunk
  jj git push     --revisions @-
  """

[tool.pborocz.deploy]
environment_files = [
  ["coctione_libri.secrets.toml", ".secrets.toml"],
]
server = "gunicorn"


[tool.ruff]
target-version = "py311"
line-length = 120
lint.ignore = [
  "COM812",  # OBO of ruff format but not sure where this is an issue.
  "D100",    # Ok, I hate the 'Missing docstring in public module' message, sue me!
  "D101",    # Ok, I hate the 'Missing docstring in public class'    "
  "D102",    # Ok, I hate the 'Missing docstring in public method'   "
  "D103",    # Ok, I hate the 'Missing docstring in public function' "
  "D104",    # Ok, I hate the 'Missing docstring in public package'  "
  "D105",    # Ok, I hate the 'Missing docstring in magic method'    "
  "D107",    # Ok, I hate the 'Missing docstring in __init__ method' "
  "D203",    # Get rid of requirement for blank line before class docstring (conflicts with linter)
  "D211",    # Get rid of conflict with D203
  "D213",    # Get rid of conflict with D212 (leaving D212 active.)
  "E402",    # Get rid of message about imports not being at the top (need for flask blueprints)
  "F401",    # Allows for imports without use (e.g. __init__.py)
  "RUF012",  # Something to do with default values on bunnet class variables not being typed.
]
lint.select = [
  # Which Ruff suites are we running?
  # (presented in order from the Ruff documentation page)
  "F",                          # Pyflakes
  "E", "W",                     # Pycodestyle (Errors and Warnings respectively)
  "C90",                        # Mccabe
  "I",                          # Isort
  "D",                          # Pydocstyle
  "UP",                         # pyupgrade
  "N",                          # pep8-naming
  "YTT",                        # flake8-2020
  # "ANN",                      # flake8-annotations (ie. type annotations!)
  # "S",                        # flake8-bandit
  # "BLE",                      # flake8-blind-except
  # "FBT",                      # flake8-boolean-trap
  "B",                          # flake8-bugbear
  # "A",                        # flake8-builtins (NO! We use "id" as an attribute, sue me...)
  "C4",                         # flake8-comprehensions
  "T10",                        # flake8-debugger
  # "EM",                       # flake8-errmsg
  # "ISC",                      # flake8-implicit-str-concat
  # "ICN",                      # flake8-import-conventions
  # "T20",                      # flake8-print (NO! Removes all print statements!!)
  # "PT",                       # flake8-pytest-style
  "Q",                          # flake8-quotes
  # "RET",                      # flake8-return
  # "SIM",                      # flake8-simplify
  # "TID",                      # flake8-tidy-imports
  # "ARG",                      # flake8-unused-arguments
  # "DTZ",                      # flake8-datetimez
  # "ERA",                      # eradicate
  # "PD",                       # pandas-vet
  # "PGH",                      # pygrep-hooks
  "PLC", "PLE", "PLR", "PLW",   # pylint
  # "PIE",                      # flake8-pie
  "COM",                        # flake8-commas
  "RUF",                        # Ruff-specific rules
]

[tool.ruff.lint.mccabe]
max-complexity = 12

[tool.ruff.lint.per-file-ignores]
"config.py" = [
  "N802",  # We want all Config properties to be uppercase (even if from a method)
  "N805",  # We have classmethods defined that use 'cls' as arg, not 'self'!
]

[tool.poe]
verbosity = 0

[tool.poe.tasks]
import = "uv run python ./app/cli/import_pdf.py"
dynaconf_list = "dynaconf -i config.settings list"
build_css = " sass --update app/static/css/sass/styles.scss app/static/css/coctione_libri.css"
sass_watch = "sass --watch  app/static/css/sass/styles.scss app/static/css/coctione_libri.css"
db_quality = "uv run python ./app/cli/db_quality.py"

[tool.poe.tasks.import_recipes_development]
interpreter = "fish"
shell = """
  uv run python -c "import tomli_w"
  uv run python ./app/cli/import_from_raindrop.py -d development -a import_existing_pdfs
  uv run python ./app/cli/import_from_raindrop.py -d development -a import_new_pdfs
"""

[tool.poe.tasks.dev_run_local]
interpreter = "fish"
shell = """
  set -x FLASK_ENV "development"
  sass --update app/static/css/sass/styles.scss app/static/css/coctione_libri.css
  uv run flask run --debug --host localhost --port 5001 --cert=../https_local/cert.pem --key=../https_local/key.pem
  """

[tool.poe.tasks.dev_run_production]
interpreter = "fish"
shell = """
  set -x FLASK_ENV "production"
  uv run flask run --debug --host localhost --port 5001 --cert=../https_local/cert.pem --key=../https_local/key.pem
"""

[tool.poe.tasks.backup_local]
interpreter = "fish"
shell = """
  echo "Doing dump from local database..."
  mkdir -p ./__backups__/working
  mongodump --db=coctione_libri_development --out=./__backups__/working

  echo "Compressing to single backup file..."
  set backup_filename (date +"backup_local_%Y%m%dT%H%M.tar.gz")
  tar -czf ./__backups__/$backup_filename ./__backups__/working
  rm                                      ./__backups__/working
  """

[tool.poe.tasks.backup_production]
#
# Alternatively: const command = `mongodump --uri "${process.env.BACKUP_MONGO_URI}" --gzip --archive=${path}`;
# as taken from: https://github.com/andresfiloso/mongo-s3-backup/blob/main/src/backup.ts
#
interpreter = "fish"
shell = """
  mkdir -p ./__backups__/working
  if not set -q mongodb; or not string length -q $mongodb
	  echo "Sorry, environment variable: 'mongodb' is either not set or is empty...please check .envrc!"
	  exit 1
  end

  echo "Doing dump from PRODUCTION database..."
  mongodump --db=coctione_libri --out=./__backups__/working --uri=$mongodb

  echo "Compressing to single backup file..."
  set backup_filename (date +"backup_production_%Y%m%dT%H%M.tar.gz")
  tar -czf ./__backups__/$backup_filename ./__backups__/working
  rm                                      ./__backups__/working
"""

[tool.poe.tasks.restore]
interpreter = "fish"
args = ["db_from", "db_to", "backup_directory_path"]
shell = """
  # Example: poe restore --db_from coctione_libri --db_to coctione_libri_development --backup_directory_path ./__backups__/working
  # mkdir -p ./__backups__/working
  # tar -xzf {$backup_directory_path} -C ./__backups__/working
  # mongorestore --nsInclude={$db_from}.\\* --nsFrom={$db_from}.\\* --nsTo={$db_to}.\\* {$backup_directory_path}
  # echo Restoring from {$backup_directory_path}/{$db_from} into {$db_to}.
  # mongorestore --gzip --archive="./backup_production_20250330T1654.tar.gz" --nsFrom="coctione_libri.*" --nsTo="coctione_libri_wasabi.*"
  # mongorestore --verbose --dir="./working"
  #
  # 2025-04-16: Finally got this work AFTER:
  # $ tar -xzf {$backup_directory_path} -C ./__backups__/working
  # and running from the shell instead from here in Poe.
  # $ mongorestore --verbose --dir=./working --nsFrom=coctione_libri.\\* --nsTo=coctione_libri_wasabi.\\*"
  """
