[default]
session_cookie_secure=true
remember_cookie_secure=true

[development]
debug_tb_enabled=true
debug_tb_intercept_redirects=false
flask_debug=true
log_level="debug"
mongo_db="mongodb://127.0.0.1:27017/coctione_libri_development?directConnection=true&serverSelectionTimeoutMS=2000&appName=coctione_libri_development"

[production]
flask_debug=false
log_level="info"
# Not here...it's a secret!
